### ISSUE TITLE
Missing DSA key preventing startup.

### ISSUE THREAD

**Issue by kurron** [corpusops/docker-sshd#1]
Image ID `289041806505` is failing to start with this message:

```
rkurr@andoria:~/ssh-ostk$ docker-compose --verbose up
[+] Running 2/2
 ⠿ Network ssh-ostk_default  Created                                                                                                                       0.0s
 ⠿ Container sshd            Created                                                                                                                       4.1s
Attaching to sshd
sshd  | frep /etc/ssh/sshd_config.in:/etc/ssh/sshd_config --overwrite
sshd  | >> Generating new host keys
sshd  | ssh-keygen: generating new host keys: RSA ECDSA ED25519 
sshd  | >>> Fingerprints for dsa host key
sshd  | ssh-keygen: /etc/ssh/keys/ssh_host_dsa_key: No such file or directory
sshd exited with code 255
```
I'm using Docker Compose to start the container. This has been working fine for months so I'm assuming the current image somehow broke something.

```yaml
version: '3.6'
services:
  sshd:
    image: corpusops/sshd:latest
    container_name: sshd
    ports:
      - 10022:22
    environment:
      - SSH_USERS=ftp:1000:1000:ftp
      - SFTP_MODE=true
      - SFTP_CHROOT=/home/ftp
      - MAX_RETRY=5
      - UIDS_START=1000
      - LOGIN_SHELL=/bin/bash
      - SYNC_SSHKEYS_TIMER=480
    volumes:
      - type: tmpfs
        target: /home/ftp
```
It has failed for me on both MacOS Ventura and Ubuntu 22.10 using Docker Compose v2.15.1 and Docker Engine 20.10.23.
